[build]
buildCommand = "npm install && npm run build && composer install --no-dev --optimize-autoloader --no-interaction && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan storage:link --force"

[deploy]
startCommand = "php artisan migrate --force && php -S 0.0.0.0:$PORT -t public"

[environment]
NODE_ENV = "production"
APP_ENV = "production"
APP_DEBUG = "false"
APP_URL = "https://jackbaba-production.up.railway.app"
FILESYSTEM_DISK = "cloudinary"
SESSION_DRIVER = "file"
SESSION_LIFETIME = "120"
SESSION_SECURE_COOKIE = "true"
SESSION_SAME_SITE = "lax"
SESSION_EXPIRE_ON_CLOSE = "false"
